[project]
name = "blank-app-template"
version = "0.1.0"
description = "A simple Streamlit app template."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.60.0",
    "pymupdf",
    "PyPDF2",
    "inflect",
    "num2words",
    "pypandoc",
    "datetime",
    "fitz",
]

[tool.uv]
package = false
